autoreg/arf/arf/urls.py
# $Id$

from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path


urlpatterns = i18n_patterns(
    path('', include('autoreg.arf.arf.urlsubs'))
)

autoreg/arf/urls.py
# $Id$

from django.conf.urls import patterns, include

urlpatterns = patterns('autoreg.arf.whois.views',
    #(r'^whois/(?P<fqdn>[A-Za-z0-9.-]+)$', 'domain'),
    #(r'^whois/(?P<id>\d+)$', include('domain')),
    #(r'^contact/(?P<handle>[A-Z0-9]+)$', 'contact'),
    #(r'^contact/(?P<handle>[A-Z0-9]+)/$', 'contact'),
    (r'^', include('autoreg.arf.urlsubs')),
)

urlpatterns += patterns('',
    # Uncomment this for admin:
#    (r'^admin/', include('django.contrib.admin.urls')),
)

autoreg/arf/whois/models.py
# $Id$

from __future__ import absolute_import


from django.db import models
from django.utils import timezone


from autoreg.whois.db import country_from_name


class Whoisdomains(models.Model):
    id = models.AutoField(primary_key=True)
    fqdn = models.CharField(max_length=255, unique=True)
    created_on = models.DateTimeField(default=timezone.now)
    updated_by = models.CharField(max_length=64)
    updated_on = models.DateTimeField(default=timezone.now)
    class Meta:
        db_table = 'whoisdomains'
        ordering = ['fqdn']
    def __str__(self):
        return self.fqdn
    class Admin:
        pass

class ContactTypes(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    class Meta:
        db_table = 'contact_types'
        ordering = ['name']
    def __str__(self):
        return self.name

class Contacts(models.Model):
    id = models.AutoField(primary_key=True)
    handle = models.CharField(max_length=20, unique=True)
    exthandle = models.CharField(max_length=20, null=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=80)
    addr = models.CharField(max_length=400)
    country = models.CharField(max_length=2)
    phone = models.CharField(max_length=40, null=True)
    fax = models.CharField(max_length=40, null=True)
    passwd = models.CharField(max_length=250)
    created_on = models.DateTimeField(default=timezone.now)
    updated_by = models.CharField(max_length=64)
    validated_on = models.DateTimeField(default=timezone.now, null=True)
    updated_on = models.DateTimeField(default=timezone.now)
    private = models.BooleanField(default=False)
    class Meta:
        db_table = 'contacts'
        ordering = ['handle']
    def __str__(self):
        return self.name or ''
    def initial_form(self):
        """Return dictionary for initial fields of contact forms"""
        adlist = self.addr.rstrip().split('\n')
        initial = { 'pn1': self.name,
                    'em1': self.email,
                    'ph1': self.phone,
                    'fx1': self.fax,
                    'private': self.private }
        n = 1
        lastk = None
        for i in adlist:
          lastk = 'ad%d' % n
          initial[lastk] = i
          n += 1
        if self.country is not None:
          initial['ad6'] = self.country
        elif lastk and lastk != 'ad6':
          co = country_from_name(initial[lastk])
          if co:
            # For "legacy" contact records, if the last address line
            # looks like a country, convert it to an ISO country code
            # and move it to the 'ad6' field in the form.
            initial['ad6'] = co
            del initial[lastk]
        return initial

    class Admin:
        search_fields = ['handle']
        list_display = ('handle', 'name')

class Otp(models.Model):
    id = models.AutoField(primary_key=True)
    contact = models.OneToOneField(Contacts, on_delete=models.CASCADE)
    secret = models.CharField(max_length=16, null=True)
    codes = models.CharField(max_length=250, null=True)
    active = models.BooleanField(default=False, null=True)
    class Meta:
        db_table = 'otp'

class DomainContact(models.Model):
    id = models.AutoField(primary_key=True)
    whoisdomain = models.ForeignKey(Whoisdomains, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contacts, on_delete=models.CASCADE)
    contact_type = models.ForeignKey(ContactTypes, on_delete=models.CASCADE)
    created_on = models.DateTimeField()
    class Meta:
        db_table = 'domain_contact'
    class Admin:
        pass
    def __str__(self):
        return "%s/%s/%s" % (self.contact.handle, self.contact_type.name, self.whoisdomain.fqdn)

class WhoisdomainsHist(models.Model):
    id = models.IntegerField(primary_key=True)
    whoisdomain_id = models.IntegerField()
    fqdn = models.CharField(max_length=255)
    created_on = models.DateTimeField()
    updated_by = models.CharField(max_length=64)
    updated_on = models.DateTimeField()
    deleted_on = models.DateTimeField()
    class Meta:
        db_table = 'whoisdomains_hist'

class ContactsHist(models.Model):
    id = models.IntegerField(primary_key=True)
    contact_id = models.IntegerField()
    handle = models.CharField(max_length=20)
    exthandle = models.CharField(max_length=20, null=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=80)
    addr = models.CharField(max_length=400)
    phone = models.CharField(max_length=40, null=True)
    fax = models.CharField(max_length=40, null=True)
    passwd = models.CharField(max_length=250)
    created_on = models.DateTimeField()
    updated_by = models.CharField(max_length=64)
    updated_on = models.DateTimeField()
    deleted_on = models.DateTimeField()
    private = models.BooleanField(default=False)
    class Meta:
        db_table = 'contacts_hist'

class DomainContactHist(models.Model):
    id = models.AutoField(primary_key=True)
    whoisdomain_id = models.IntegerField()
    contact_id = models.IntegerField()
    contact_type = models.ForeignKey(ContactTypes, on_delete=models.CASCADE)
    created_on = models.DateTimeField()
    deleted_on = models.DateTimeField()
    class Meta:
        db_table = 'domain_contact_hist'

class Tokens(models.Model):
    id = models.AutoField(primary_key=True)
    contact_id = models.IntegerField()
    token = models.CharField(max_length=16, null=True)
    date = models.DateTimeField(default=timezone.now)
    expires = models.DateTimeField()
    action = models.CharField(max_length=10, null=True)
    args = models.CharField(max_length=200, null=True)
    class Meta:
        db_table = 'arf_tokens'

class Iso3166Countries(models.Model):
    iso_id = models.CharField(primary_key=True, max_length=2)
    lang = models.CharField(max_length=2)
    name = models.CharField(max_length=60)
    class Meta:
        db_table = 'iso3166_countries'
    def __str__(self):
        return self.iso_id
    class Admin:
        pass

class Admins(models.Model):
    id = models.AutoField(primary_key=True)
    login = models.CharField(max_length=16, unique=True)
    contact = models.ForeignKey(Contacts, on_delete=models.CASCADE)
    class Meta:
        db_table = 'admins'
        ordering = ['login']
    class Admin:
        pass
    def __str__(self):
        return self.login


def check_is_admin(handle):
  if not handle:
    return False
  return Admins.objects.filter(contact__handle=handle.upper()).exists()

def log(handle, action, message=None):
  l = Log(contact=Contacts.objects.get(handle=handle), action=action,
          message=message)
  l.save()

autoreg/arf/whois/views.py
# $Id$

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals


import crypt
import datetime
import io
import random
import re
import socket
import time


import django.contrib.auth
from django.core.exceptions import SuspiciousOperation, PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import connection
from django import forms
from django.forms.widgets import PasswordInput
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy, ugettext as _
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_http_methods


from autoreg.common import domain_delete, fqdn_to_idna
from autoreg.conf import HANDLESUFFIX
import autoreg.dns.db
from autoreg.util import decrypt, encrypt, pwcrypt
from autoreg.whois.db import \
  suffixstrip,suffixadd,Domain,check_handle_domain_auth,handle_domains_dnssec, \
  countries_get
from autoreg.conf import FROMADDR


from ..util import render_to_mail
from ..logs.models import log, Log
from .decorators import blackout, login_active_required, check_handle_fqdn_perms
from .models import Whoisdomains,Contacts,Tokens,DomainContact, check_is_admin
from . import otp
from . import token


RESET_TOKEN_HOURS_TTL = 24
EMAIL_TOKEN_HOURS_TTL = 72
VAL_TOKEN_HOURS_TTL = 72
RESET_TOKEN_TTL = RESET_TOKEN_HOURS_TTL*3600
EMAIL_TOKEN_TTL = EMAIL_TOKEN_HOURS_TTL*3600
VAL_TOKEN_TTL = VAL_TOKEN_HOURS_TTL*3600

domcontact_choices = [('technical', ugettext_lazy('technical')),
                      ('administrative', ugettext_lazy('administrative')),
                      ('zone', ugettext_lazy('zone'))]


#
# Helper functions
#


class Country(object):
  def __iter__(self):
    self.c = countries_get(connection.cursor())
    return self.c.__iter__()


def countries_get_lazy():
  """Lazy evaluation for the country list, so it is not run at module import."""
  return Country


#
# Forms
#

class contactbyemail_form(forms.Form):
  email = forms.EmailField(max_length=100)

class contactbyhandle_form(forms.Form):
  handle = forms.CharField(max_length=20, initial=HANDLESUFFIX,
                           help_text=ugettext_lazy('Your handle'))

class contactbydomain_form(forms.Form):
  domain = forms.CharField(max_length=80, initial='.eu.org',
                           help_text=ugettext_lazy('Domain'))

class contactchange_form(forms.Form):
  pn1 = forms.RegexField(max_length=60, label=ugettext_lazy("Name"),
              regex='^[a-zA-Z \.-]+\s+[a-zA-Z \.-]')
  em1 = forms.EmailField(max_length=64, label=ugettext_lazy("E-mail"))
  ad1 = forms.CharField(max_length=80, label=ugettext_lazy("Organization"))
  ad2 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 1)"))
  ad3 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 2)"),
                        required=False)
  ad4 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 3)"),
                        required=False)
  ad5 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 4)"),
                        required=False)
  ad6 = forms.ChoiceField(initial='', label=ugettext_lazy("Country"),
                          choices=countries_get_lazy())
  ph1 = forms.RegexField(max_length=30, label=ugettext_lazy("Phone"),
                         regex='^\+?[\d\s#\-\(\)\[\]\.]+$', required=False)
  fx1 = forms.RegexField(max_length=30, label=ugettext_lazy("Fax"),
                         regex='^\+?[\d\s#\-\(\)\[\]\.]+$', required=False)
  private = forms.BooleanField(label=ugettext_lazy("Private (not shown in the public Whois)"), required=False)

class contact_form(contactchange_form):
  p1 = forms.CharField(max_length=64, label=ugettext_lazy('Password'),
                       required=False, widget=PasswordInput)
  p2 = forms.CharField(max_length=64, label=ugettext_lazy('Confirm Password'),
                       required=False, widget=PasswordInput)
  policy = forms.BooleanField(label="I accept the Policy", required=True)

class registrant_form(forms.Form):
  # same as contactchange_form minus the email field
  pn1 = forms.RegexField(max_length=60, label=ugettext_lazy("Name"),
              regex='^[a-zA-Z \.-]+\s+[a-zA-Z \.-]')
  # disabled until we get rid of the RIPE model (unshared registrant records)
  #em1 = forms.EmailField(max_length=64, label="E-mail", required=False)
  ad1 = forms.CharField(max_length=80, label=ugettext_lazy("Organization"))
  ad2 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 1)"))
  ad3 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 2)"),
                        required=False)
  ad4 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 3)"),
                        required=False)
  ad5 = forms.CharField(max_length=80, label=ugettext_lazy("Address (line 4)"),
                        required=False)
  ad6 = forms.ChoiceField(initial='', label=ugettext_lazy("Country"),
                          choices=countries_get_lazy())
  ph1 = forms.RegexField(max_length=30, label=ugettext_lazy("Phone"),
                         regex='^\+?[\d\s#\-\(\)\[\]\.]+$', required=False)
  fx1 = forms.RegexField(max_length=30, label=ugettext_lazy("Fax"),
                         regex='^\+?[\d\s#\-\(\)\[\]\.]+$', required=False)
  private = forms.BooleanField(label=ugettext_lazy("Private (not shown in the public Whois)"), required=False)

class domcontact_form(forms.Form):
  contact_type = forms.ChoiceField(choices=domcontact_choices,
                                   label=ugettext_lazy("type"))
  handle = forms.CharField(max_length=20, initial=HANDLESUFFIX)

class contactlogin_form(forms.Form):
  handle = forms.CharField(max_length=20, initial=HANDLESUFFIX,
                           help_text=ugettext_lazy('Your handle'))
  password = forms.CharField(max_length=64,
                             help_text=ugettext_lazy('Your password'),
                             widget=PasswordInput)

class resetpass_form(forms.Form):
  resettoken = forms.CharField(max_length=30,
                               label=ugettext_lazy('Reset Token'))
  pass1 = forms.CharField(max_length=64,
                          label=ugettext_lazy('New Password'),
                          widget=PasswordInput)
  pass2 = forms.CharField(max_length=64,
                          label=ugettext_lazy('Confirm Password'),
                          widget=PasswordInput)

class changemail_form(forms.Form):
  token = forms.CharField(max_length=30)

class chpass_form(forms.Form):
  pass0 = forms.CharField(max_length=64,
                          label=ugettext_lazy('Current Password'),
                          widget=PasswordInput)
  pass1 = forms.CharField(max_length=64,
                          label=ugettext_lazy('New Password'),
                          widget=PasswordInput)
  pass2 = forms.CharField(max_length=64,
                          label=ugettext_lazy('Confirm Password'),
                          widget=PasswordInput)

#
# 'view' functions called from urls.py and friends
#

#
# public pages
#

@require_http_methods(["GET", "POST"])
@blackout
def login(request):
  """Login page"""
  if request.method == "GET":
    next = request.GET.get('next', None)
    if request.user.is_authenticated and request.user.is_active:
      return HttpResponseRedirect(reverse(domainlist))
    f = contactlogin_form()
    form = f.as_table()
    request.session.set_test_cookie()
    vars = { 'form': form, 'next': next }
    return render(request, 'whois/login.html', vars)

  if request.method == "POST":
    next = request.POST.get('next', reverse(domainlist))
    vars = {'next': next}
    if request.user.is_authenticated:
      #django.contrib.auth.logout(request)
      return HttpResponseRedirect(next)
    if not request.session.test_cookie_worked():
      vars['msg'] = _("Please enable cookies")
      vars['form'] = contactlogin_form().as_table()
      return render(request, 'whois/login.html', vars)
    else:
      #request.session.delete_test_cookie()
      pass
    handle = request.POST.get('handle', '').upper()
    password = request.POST.get('password', '')
    handle = suffixstrip(handle)

    vars = {'next': request.path,
            'form': contactlogin_form().as_table()}
    user = django.contrib.auth.authenticate(username=handle, password=password)
    if user is not None:
      c = Contacts.objects.filter(handle=handle)
      if c.count() != 1:
        raise SuspiciousOperation
      v = c[0].validated_on
      if not v:
        vars['msg'] = _("You need to validate your account. " \
                      "Please check your e-mail for the validation link.")
      elif not user.is_active:
        vars['msg'] = _("Sorry, your account has been disabled")
      elif otp.totp_is_active(handle):
        # send the user to a 2nd page for two-factor authentication
        request.session['1fa'] = handle
        return HttpResponseRedirect(reverse('login2fa'))
      else:
        # no OTP to process, login complete
        log(handle, action='login')
        django.contrib.auth.login(request, user)
        return HttpResponseRedirect(next)
    else:
      vars['msg'] = _("Your username and/or password is incorrect")
    return render(request, 'whois/login.html', vars)

@require_http_methods(["GET", "POST"])
@blackout
def contactbydomain(request, fqdn=None):
  if request.method == "GET" and fqdn is None:
    f = contactbydomain_form()
    form = f.as_table()
    vars = { 'form': form }
    return render(request, 'whois/contactdomainform.html', vars)
  elif request.method == "POST" or fqdn is not None:
    fqdn = fqdn or request.POST.get('domain', '')
    handles = DomainContact.objects \
               .filter(whoisdomain_id__fqdn=fqdn.upper(),

autoreg/arf/templates/whois/2fa-set.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Two-factor Authentication" %}{% endblock %}
{% block form %}

<div>
{% trans "Two-factor Authentication is set." %}
</div>
<div id="id_otpmain">
  <form id="id_otpform" class="form" action="{% url '2fa-clear' %}" METHOD="POST">
  {% csrf_token %}
  <label for="id_otp"></label>{% trans "Enter code to deactivate" %}: <input type="text" name="otp" maxlength="8" autocomplete="off" required id="id_otp" /><span class="helptext">{% trans "One-Time Password" %}</span><br>
  <input class="action" type="submit" name="deactivate" value="{% trans "Deactivate" %}">
  </form>

  <div>{% blocktrans %}You currently have {{ ncodes }} recovery codes remaining. You can regenerate new codes, cancelling the current ones.{% endblocktrans %}</div>
  <form id="id_otpnewrecoveryform" class="form" action="{% url '2fa-newrecovery' %}" METHOD="POST">
  {% csrf_token %}
  <input class="action" type="submit" name="newrecovery" value="{% trans "Generate new recovery codes" %}">
  </form>
</div>
{% endblock %}

autoreg/arf/templates/whois/2fa-setup1.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Recovery Codes" %}{% endblock %}
{% block form %}

<div id="id_recovery">
  <div id="id_recoverytitle">{% trans "Please store the following recovery codes in a safe place." %}</div>
  <ul id="id_recoverylist">{% for c in codes %}<li>{{ c }}</li> {% endfor %}</ul>
</div>

<a class="action" href="{% url nexturl %}">{{ nextlabel }}</a>
{% endblock %}

autoreg/arf/templates/whois/2fa-setup2.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Two-factor Authentication" %}{% endblock %}
{% block form %}

<div id="id_otpcode">
  <div id="id_code">{% trans "New code:" %} <span id="id_otpsecret">{{ secret }}</span></div>
  <img id="id_qrcode" src="data:image/png;base64,{{ qrcode }}">
</div>

<FORM id="id_otpform" class="form" ACTION="{{ posturi }}" METHOD="POST">
{% csrf_token %}
<label for="id_otp"></label>{% trans "Code to check and confirm setup:" %} <input type="text" name="otp" maxlength="8" autocomplete="off" required id="id_otp" /><span class="helptext">{% trans "One-Time Password" %}</span><br>
<INPUT class="action" TYPE="submit" NAME="totpset" VALUE="{% trans "Activate New Code" %}">
</FORM>
{% endblock %}

autoreg/arf/templates/whois/chpass.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Password Change" %}{% endblock %}
{% block msg %}{% if msg %}{{ msg }}
{% endif %}{% endblock %}
{% block form %}
<h1>{% trans "Password Change" %}</h1>
<FORM class="form" ACTION="{{ posturi }}" METHOD="POST">
{% csrf_token %}
<TABLE>
{{ form }}
</TABLE>
<INPUT class="action" TYPE="submit" NAME="change" VALUE="{% trans "Change Password" %}">
</FORM>
{% endblock %}

autoreg/arf/templates/whois/contactdomain.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ title }}{% endblock %}
{% block form %}
{% for h in handles %}
<a href="{% url 'makeresettoken' h %}">{% blocktrans %}My handle is {{ h }}{{ suffix }}{% endblocktrans %}</a>.<BR>
{% endfor %}
{% endblock %}

autoreg/arf/templates/whois/contactnotfound.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ title }}{% endblock %}
{% block msg %}
{% blocktrans %}Contact <span class="handle">{{ ehandle }}</span> not found.{% endblocktrans %}
{% if next %}<br><a href="{{ next }}">{% trans "Continue" %}</a>{% endif %}
{% endblock %}

autoreg/arf/templates/whois/contactvalidate.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Contact Validation" %}{% endblock %}
{% block msg %}
<h1>{% trans "Contact Validation" %}</h1>
{% trans "Please check that the following is correct, then press the <strong>Validate</strong> button." %}
<hr>
{% trans "Contact handle: " %}<span class="handle">{{ handle }}</span><br>
{% trans "Contact email: " %}<span class="email">{{ email }}</span><br>
{% endblock %}
{% block form %}
<FORM ACTION="{{ posturi }}" METHOD="POST">
{% csrf_token %}
<INPUT TYPE="hidden" NAME="valtoken" VALUE="{{ valtoken }}">
<INPUT class="action" TYPE="submit" NAME="submit" VALUE="Validate">
</FORM>
{% endblock %}

autoreg/arf/templates/whois/domainedit.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Domain Edit" %}{% endblock %}
{% block msg %}{% if msg %}{{ msg }}<hr>
{% endif %}{% endblock %}
{% block form %}

{% blocktrans %}Whois data for domain <span class="domain">{{ idna }}</span><P>
Created on: {% endblocktrans %}{{ whoisdomain.created_on|date:"o-m-d H:i" }}
<pre class="whoisdisplay">
{{ whoisdisplay }}</pre>

<div class="domainedits">
<strong>{% trans "Edit" %}</strong>
<table>
<tr>
<td><A class="miniaction" HREF="{% url 'contactchange' fqdn %}">{% trans "Registrant" %}</A>
<td><A class="miniaction" HREF="{% url 'domainns' fqdn %}">{% trans "Nameservers" %}</a>
<td><A class="miniaction" HREF="{% url 'domainhist' fqdn %}">{% trans "History" %}</a>
<td>{% if has_ns and can_ds %}<A class="miniaction" HREF="{% url 'domainds' fqdn %}">DNSSEC</A>{% endif %}
<td>{% if registry_hold and end_grace_period %}
<form action="{% url 'domainundelete' fqdn %}" method="POST">
{% csrf_token %}
<INPUT class="miniaction" TYPE="submit" NAME="undel" VALUE="{% trans "Undelete (until" %} {{ end_grace_period|date:"o-m-d" }})">
{% else %}
<td><form action="{% url 'domaindelete' fqdn %}" method="POST">
{% csrf_token %}
<INPUT class="miniaction" TYPE="submit" NAME="del" VALUE="{% trans "Delete Domain" %}">
{% endif %}
</form>
</table>
</div>

<div class="contactedits">
 <strong>Contacts</strong><P>
 <div class="contactarray">
{% for f in formlist %}
  <FORM ACTION="{{ f.posturi }}" METHOD="POST">
  {% csrf_token %}
  <INPUT TYPE="hidden" NAME="contact_type" VALUE="{{ f.contact_type }}">
  <INPUT TYPE="hidden" NAME="handle" VALUE="{{ f.handle }}">
  <span class="descr">{{ f.contact_type }}</span>
  <span class="descr"><span class="handle">{{ f.handle }}</span></span>
  <INPUT class="miniaction" TYPE="submit" NAME="submitd" VALUE="{% trans "Remove" %}">
  </FORM>
{% endfor %}
  <FORM ACTION="{{ addform.posturi }}" METHOD="POST">
  {% csrf_token %}
  {% for field in addform.domcontact_form %}
    <span class="descr">{{ field }}</span>
  {% endfor %}
  <INPUT class="miniaction" TYPE="submit" NAME="submita" VALUE="{% trans "Add" %}">
  </FORM>
 </div>
</div>

{% endblock %}

autoreg/arf/templates/whois/domainnotfound.html
Domain <strong><tt>{{ fqdn }}</tt></strong> not found.

autoreg/arf/templates/whois/emailchanged.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Email address changed" %}{% endblock %}
{% block h1title %}{% trans "Email address changed" %}{% endblock %}
{% block msg %}
{% blocktrans %}Email address has been successfully set to <span class="email">{{ newemail }}</span>.{% endblocktrans %}
{% if next %}<br><a href="{{ next }}">{% trans "Continue" %}</a>{% endif %}
{% endblock %}

autoreg/arf/templates/whois/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ sitename }}{% endblock %}
{% block msg %}{% if msg %}{{ msg }}
{% endif %}{% endblock %}
{% block form %}
<FORM class="form" id="id_loginform" ACTION="{{ posturi }}" METHOD="POST">
{% csrf_token %}
<div>
<label for="id_handle">{% trans "Handle" %}</label>
<input id="id_handle" maxlength="15" name="handle" type="text" value="{{suffix }}" />
<span class="helptext">{% trans "Your handle" %}</span>
</div>
<div>
<label for="id_password">{% trans "Password" %}</label><input id="id_password" maxlength="30" name="password" type="password" />
<span class="helptext">{% trans "Your password" %}</span>
</div>
{% if next %}<INPUT TYPE="hidden" NAME="next" VALUE="{{ next }}">
{% endif %}
<INPUT class="action" TYPE="submit" NAME="login" VALUE="{% trans "Login" %}">
</FORM>
<a class="action" href="{% url 'contactcreate' %}"><span>{% trans "Register" %}</span></a>
<div class="loginhelp">
<strong>{% trans "You can't remember the contact handle or password?" %}</strong>
<ul>
<li>{% url 'makeresettoken' as urlreset %}{% blocktrans %}If you forgot your password or never had one, <a href="{{ urlreset }}">set a new password here</a>.{% endblocktrans %}
<li>{% url 'contactbydomain' as urlbydom %}{% blocktrans %}If you remember your domain name, you can <a href="{{ urlbydom }}">find your contact handle</a>.{% endblocktrans %}
</ul>
</div>
{% endblock %}

autoreg/arf/templates/whois/passchanged.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Password changed" %}{% endblock %}
{% block msg %}
{% blocktrans %}Password has been successfully changed for <span class="handle">{{ ehandle }}</span>.{% endblocktrans %}
{% if next %}<br><a href="{{ next }}">{% trans "Continue" %}</a>{% endif %}
{% endblock %}